openair-project/openair

R/importAURN.R
Hi there! When you retrieve numerous data sets, the function crashes as it reaches the maximum number of connections open. You could avoid this limitation by using closeAllConnections() rather than close(con) in line 334.
=> Close all connections in importAURN.R

R/windRose.R
With a slight modification the  'annotate = TRUE' behavior is retained; however, 'annotate  = custom.annotation' will allow the user to add any desired annotation.    I am working on a windy data where adding calm=0% to every plot does not make much sense.  This can remove the calm and replace it with anything.
This would be useful if the user, say wanted to annotate total n using  'annotate = paste("total n =", length(ws))'.
=> Expanding annotation ability in windrose

R/windRose.R
These changes mimic the behavior of the older versions.  There is one alteration that a novice user should probably not be using:
This produces no max interval.  It does warn if the maximum was exceeded.
windRose(mydata, breaks = list("noMaxInterval"))
no max interval, but is similar to breaks = 6. 
windRose(mydata, breaks = list("noMaxInterval",6))
no max interval, but is similar to breaks = c(1,2,3). 
windRose(mydata, breaks = list("noMaxInterval",1,2,3))
-or-
windRose(mydata, breaks = list("noMaxInterval",c(1,2,3)))
=> altered behavior of the breaks guards

R/importKCL.R, R/importSAQN.R, R/importTraj.R
Currently connections aren't closed if the requested data file doesn't exist. This is a problem when we want to get data from all sites, using something like this:
```r
sites <- importMeta(source="kcl")$code
data <- importKCL(site=sites, year=2001:2004)
```
This eventually leads to the ``all connections are in use`` error (as reported in #167). This PR fixes the issue by always closing the connection. The importKCL function has been tested with this change and it resolves the issue.
=> Close connections even on failure

R/summaryPlot.R
Currently the `summaryPlot` function doesn't do what's expected when there are two sites in the data frame. This commit fix this issue.
=> fix summaryPlot when there're two sites

R/timeAverage.R
Just applying the same fix already in place for start.date. mydata[[type]] causes an error when there are multiple grouping variables.
=> make end.date compatible with type of size > 1

R/trajCluster.R
As written, `trajCluster(traj, plot = FALSE)` errors as it tries to assign the non-existent `plt` to the `output` list. 
This is a fix such that, when `plot = FALSE`, only the clustered data frame is returned.
It could alternatively still return a list of `data` and `call` to be more consistent with its `plot = TRUE` behaviour, but just returning the data frame feels more practical (e.g., it'd be easier to assign it and use it without indexing a list, and can easily be used in a `{magrittr}` pipeline).
=> Fix trajCluster where plot = FALSE

R/importUKAQ.R
Similar to https://github.com/davidcarslaw/openair/pull/187/commits/8f9ab1e622b92d9860db6835b73fa4c0383a915c but for importUKAQ-based importing (e.g., importAURN). As in the other PR, if you import a lot of sites and some are missing you can end up with a situation as in https://github.com/davidcarslaw/openair/issues/167.
Also fixed some indentation.
Tested by importing all urban sites in the UK with `importAURN()`. Previously this would lead to `Error in file(filename, "r", encoding = encoding) : all connections are in use` but with the change this does not occur.
=> Close connections on all importUKAQ-based importing functions

R/openColours.R, R/polarFreq.R, R/trajPlot.R, man/openColours.Rd, man/polarFreq.Rd, man/trajPlot.Rd
Added the "turbo" colour palette as an option to `openColours()`.
"turbo" was designed by Google to improve "jet" by having a more consistent lightness profile. It almost looks like a middle ground between "jet" and openair's "default" palette.
More info here: https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html
Note that "jet" hasn't been removed, so users can use either "jet" or "turbo".
=> Add "turbo" to openColours()

R/trajCluster.R, man/trajCluster.Rd
At the moment, the frequency stats aren't returned in the `trajCluster()` data frame, and just exist on the plot. Hard to then use them for other stuff (including in `{ggopenair}`). 
Two changes:
- Attach freq stats to `results` df
- Mention in "returns" tag what the two `data` objects are
=> feat (R/trajCluster.R): return n/freq

R/polarCluster.R, man/polarCluster.Rd
Myriad of small fixes to `polarCluster()`:
- Added the `plot.data` argument, which when `TRUE` toggles the output data to be the u/v/cluster coords to replot elsewhere. This is a bit of a selfish addition as I need this for `{ggopenair}`. The addition of `plot.data` as an argument rather than returning both at once means this isn't a breaking change, unlike the similar one done for `trajCluster()` a short while ago.
- Fixed "unidentified columns" issue noted by Defra. This wasn't a tidyverse issue - totally the opposite actually, you were referring to a data frame (`mydata`) that didn't _always_ exist (see next bullet). Now fixed and clusters are returned as factors rather than integers, in line with `trajCluster()`.
- When `n.clusters()` is a vector length > 1, the `data` object returned …
=> Various fixes and refinements to R/polarCluster.R

R/getMeta.R
Fixed issue where `importMeta()` would only show one pollutant per site when `all = TRUE`. This snuck in after the recent update allowing for multiple networks to be examined at once.
=> fix (R/getMeta.R): stop dropping pollutants

.Rbuildignore, NEWS, NEWS.md, R/getMeta.R, R/percentileRose.R, R/polarAnnulus.R, R/polarDiff.R, R/polarFreq.R, R/polarPlot.R, R/windRose.R, man/importMeta.Rd, man/percentileRose.Rd, man/polarAnnulus.Rd, man/polarDiff.Rd, man/polarFreq.Rd, man/polarPlot.Rd, man/pollutionRose.Rd, man/windRose.Rd
Added the `alpha` argument to `polarAnnulus()`, `polarFreq()`, `polarDiff()`, `percentileRose()`, `windRose()` and `pollutionRose()`. These are all useful and necessary in `openairmaps` - see https://github.com/davidcarslaw/openairmaps/commit/49af773b068591630202fd4a60ac13df92d0a862 - especially now the issue with alpha on non-Mac OS has been fixed - see https://github.com/davidcarslaw/openairmaps/commit/97cc3c736fc0206e5f68b4d0f3350f0988da3b5b.
Also:
* Fixed typo in `importMeta()` that was causing R CMD issues (no closing quotation mark).
* Updated `NEWS.md` with this alpha update.
* Deleted `NEWS` placeholder and revised `.Rbuildignore`, which seem to be legacies from a time before `NEWS.md` was allowed by CRAN.
=> Add "alpha" to directional analysis functions

DESCRIPTION, R/polarPlot.R, man/import_ukaq.Rd, man/polarCluster.Rd, man/polarDiff.Rd, man/polarPlot.Rd
Add `formula.label` argument to `polarPlot` function to allow for the complete absence of labels & useful when many panels/facets are used & resolves #340
=> Add `formula.label` argument to `polarPlot` function & #resolves #340

NEWS.md, R/openColours.R, man/openColours.Rd
Adds UK govt. analysis function palettes to openair; see <https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/>.
**Categorical:**
```r
timeProp(mydata, "nox", "o3", avg.time = "month", cols = "gaf.cat")
```
**Focus:** 
```r
calendarPlot(mydata, year = 2003, breaks = c(0, 50, Inf), cols = "gaf.focus", pollutant = "pm10")
```
**Sequential:**
```r
trendLevel(mydata, cols = "gaf.seq")
```
=> feat: add government analysis function pals to `openColours()`

NEWS.md, R/openColours.R, man/openColours.Rd
This PR makes the following refinements to `openColours()`:
- Adds three new colourblind friendly qualitative palettes based on the work of Paul Tol.
- Adds two new palettes based on the default colour palettes of Tableau and Observable Plot (useful for consistency with plots using these frameworks)
- `openColours()` will now not error when a qualitative palette is used but `n` is left at the default of `100`. Now the full palette will be returned instead. Mainly useful for using `openColours()` outside of `{openair}`.
- `openColours()` now errors if things that aren't valid R colours or `openColours()` palettes are provided.
- `openColours()` now errors if *both* valid R colours *and* `openColours()` palettes (or multiple palettes) are provided.
- refactored to group all of the …
=> feat: add new colours, fixes, and error catching to `openColours()`

NEWS.md, R/importUKAQ-utils.R, R/importUKAQ.R, man/importUKAQ.Rd
This PR extends the capabilities introduced in #350.
In short, the default `source` in `importUKAQ()` is now `NULL`. This allows `importUKAQ()` to work out the `source` on its own, where possible.
See examples:
``` r
devtools::load_all()
#> ℹ Loading openair
set.seed(123)
meta_sample <-
importMeta(year = 2023, source = "ukaq") |>
dplyr::slice_sample(n = 1, by = source)
meta_sample$code
#> [1] "TALL"  "WL1"   "NL11"  "NPT4A" "BEL5"  "WA7"
meta_sample$source
#> [1] "aurn"  "aqe"   "saqn"  "waqn"  "ni"    "local"
aq <-
importUKAQ(
year = 2023,
site = meta_sample$code
)
dplyr::count(aq, source, site, code)
#> # A tibble: 5 × 4
#>   source site                            code      n
#>   <fct>  <chr>                           <chr> <int>
#> 1 aurn   Tallington                      TALL    504 …
```
=> feat: allow UKAQ to guess `source` of `site`

DESCRIPTION, NEWS.md, R/importUKAQ.R
This PR is a small tweak to returned DAQI data. A new `band` column is appended, a factor with levels "Low", "Moderate", "High" and "Very High".
One can now therefore do:
``` r
> importUKAQ(source = "aurn", data_type = "daqi") |>
+   dplyr::count(band)
band           n
<fct>      <int>
1 Low       154959
2 Moderate    1586
3 High          92
4 Very High      5
```
=> feat: return DAQI band along with DAQI data

R/calendarPlot.R, man/calendarPlot.Rd
This PR adds a way of overwriting the font size for the annotations when `annotate = "date"`. It maintains the existing default size if no argument is passed. I've tested the results using the fork in the package I'm using.
I'm part of a team that's been building project that's using the `calendarPlot` function. Thanks for your work maintaining this project, it's definitely given us a quick way to get nice calendar plots!
We are having issues with the size of the text for dates in the plot when `annotate = "date"`. I can see there's a way to overwrite it for `annotate = "value"` but not for `"date"`. I tried setting the font size through other means, like `fontsize` or the other `par.x.text = list(cex = x)` options but I couldn't find a method that worked for the annotation text (though …
=> Add an arigument to allow for overwriting the annotation size for the date

NEWS.md, R/quickText.R, R/timePlot.R
Fixes #212.
Previously, `timePlot()` would pivot away the ws/wd columns if they were also in "pollutant".
This PR restores them to `mydata` if the user also wants to use `windflow`.
Can now create plots of wind speed with wind direction on them:
=> Fix `timePlot()` `windflow` when ws/wd are in `pollutant`

DESCRIPTION, NEWS.md, R/scatterPlot.R, R/trajLevel.R, R/trajPlot.R, man/trajLevel.Rd, man/trajPlot.Rd
Fixes #24.
Adds `grid.nx` and `grid.ny` to control the number of ticks on the map grid of `trajLevel()` and `trajPlot()`. If both are zero, the grid is omitted entirely.
`grid.ny` inherits from `grid.nx` by default, as I imagine most users will want a roughly square grid.
``` r
devtools::load_all()
#> ℹ Loading openair
trajLevel(openairmaps::traj_data, grid.nx = 20)
```
``` r
trajLevel(openairmaps::traj_data, grid.nx = 3)
```
``` r
trajLevel(openairmaps::traj_data, grid.nx = 0)
```
<sup>Created on 2025-09-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
=> Add `grid.nx` and `grid.ny` to `trajPlot()` and `trajLevel()`

NEWS.md, R/calendarPlot.R, R/timePlot.R, R/trendLevel.R, R/utilities.R, man/calendarPlot.Rd
Fixes #435 and #150. Refactor, plus:
- Adds `percentile` for use w/ `statistic = "percentile"`
- Makes `statistic = "min"` & `annotate = "ws"` work similarly to `statistic = "max"`.
- Adds `show.year` which, if only one year of data is given, simplifies the strip text to just show the month rather than e.g. "January-2000". If multiple years are given, this is ignored. Fixes #150.
That last one is nice, I think. The specific use case in that issue is for averaging over multiple years so there is no "year" to plot (maybe we can add that as an argument?), but it's also handy just to clean up the labels a bit.
=> Refine `calendarPlot()`
